YJU-OKURA/project_minori-next-deployment-repo

.github/workflows/auto-assign.yml

*  新規に作成されたIssueやプルリクエストに自動的にレビュアーやアサインを割り当てる機能を実装することで、Issueやプルリクエストの管理をより効率的に行います。
* GitHub Actionsの設定ファイル（auto-assign.yml）を作成し、新規Issueとプルリクエストの作成時に自動でアサインを行う設定を追加しました。
* なし
* `auto-assign.yml`ファイルの設定内容とその動作についてご確認いただきたいです。
* 新規Issueやプルリクエストが作成された際の自動アサインの動作を確認する必要があります。
* 関連Issue: #7 
- なし
---

自動割り当て機能のためのGitHub Actions設定の追加

---

.github/workflows/cr.yml

* Github ActionsがフォークしたリポジトリからのPRで動作しない問題を解決します。
* 'pull_request'イベントを'pull_request_target'イベントに置き換えました。これにより、フォークしたリポジトリからのPRでもGithub Actionsが動作します。
* なし
* Github Actionsの設定ファイル内で'pull_request'イベントが'pull_request_target'イベントに正しく置き換えられたかどうか。
* 新しい設定が正しく動作するかどうかを確認するために、フォークしたリポジトリから新たなPRを作成してみてください。
関連するIssue: #13 
* まだありません。
---

Github Actionsの設定変更：'pull_request'イベントを'pull_request_target'イベントに置き換え

---

.github/workflows/auto-reviewer.yml
.github/workflows/auto_fe_reviewer.yml

* 新たに作成されたプルリクエストに自動的にレビュワーを割り当てることで、レビュープロセスの効率化と管理の簡素化を実現したいと考えています。
* 主な変更点は、GitHub Actionsを使用して新たなプルリクエストに対して自動的にレビュワーを割り当てる新機能を導入したことです。
* なし
* `auto-reviewer.yml`設定ファイルの設定について特に見ていただきたいです。
* 新機能の動作を確認するために、新たなプルリクエストを作成し、自動的にレビュワーが割り当てられるかを確認する必要があります。
関連するIssue: #11 
* まだありません。
---

自動Reviewer当て機能のためのGitHub Actions設定の追加

---

yuminnk-nextjs-starter/package.json
yuminnk-nextjs-starter/yarn.lock

> 
* TypeScriptのバージョンを5.1.6に変更して、GoogleTypeScript (以下gts)を実行できるように修正しました
> 
* TypeScriptのバージョンが5.1.6に変更されます。
> 
* なし
> 
* 変更されたTypeScriptのバージョンを確認してください
> 
* なし
> #16 TypeScriptのバージョンを変更
> 
---

🔨 chore : downgrade version of typescript to v5.1.6

---

.github/workflows/auto-assign.yml
.github/workflows/openai_code_review.yml

> Github Organizationで発生したトークン問題を解決しました。適切なトークンを生成して適用しました。これにより、既存のトークン問題を解決しました。
> 新しく生成したトークンをGithub Organizationに適用しました。これにより、以前発生していたトークン問題が解決しました。
> なし
> 適用したトークンの適切性と機能についての確認が必要です。
> 適用されたトークンの機能と適切性に関するテストが必要です。
> #5 
> #7 
> #11 
---

`TOKEN`を`ADMIN_TOKEN`に更新 

---

.github/workflows/auto-reviewer.yml

> 設定ファイルへのパスが絶対パスであるため、プロジェクトの構造が変わると参照が破壊される可能性があります。そのため、相対パスを使用するように変更しました。
> 設定ファイルへのパスを絶対パスから相対パスに変更しました。
> なし
> 特になし
> 特になし
> 特になし
> 特になし
---

相対パス使用への変更

---

.github/workflows/openai_code_review.yml

OpenAIコードレビューのGitHub Actionsワークフローに対する権限設定とイベントトリガーの問題を解決したいです。これらの変更により、ワークフローの効率とセキュリティが向上し、プルリクエストに対する自動コードレビューがより正確に行われるようになります。
* issues: write 権限を追加しました。これにより、ワークフローがイシューやプルリクエストにコメントを書くことができるようになります。
* イベントトリガーを pull_request_target から pull_request に変更しました。これにより、プルリクエストに対するトリガーがより適切に行われ、セキュリティと正確性が向上します。
* ジョブの名前を test から code-review に変更しました。これにより、その目的と機能がより明確になります。
なし
新しい権限設定とイベントトリガーの適切さに注目していただきたいです。
ワークフローが正常に機能するかどうか、特に新しい権限設定についてテストが必要です。
#5  …

GitHub Actionsワークフローの権限とイベントトリガーの更新

---

src/app/globals.css

* 提供しないダークモードのコードをコメントアウトすることで、混乱を防ぎます。また、背景の色をrgb(255, 255, 255)に設定しました。
* なし 
* なし 
* なし
* なし
* #32 
* なし

💄 style : Modify root style in global.css

---

src/app/layout.tsx
src/components/navbar.tsx

* navbarが画面のサイズによって移動する問題があって、画面に固定させることで解決しました。
* navbarを画面に固定させました。
* なし
* なし 
* なし 
- #33
- [메뉴바( メニューバー)](https://trello.com/b/WIqxI1ES/minori)
- なし

navbarがサイズによって移動する問題解決

---

src/app/globals.css
src/components/dashboard/Dashboard.tsx
src/components/dashboard/TabsMapping.tsx
src/components/dashboard/index.ts
src/interfaces/group/dashboardProps.ts
src/interfaces/group/index.ts
src/interfaces/group/tabsMappingProps.ts

*  Dashboardが必要なページで簡単に使用できるComponentの提供が可能です
* Dashboardを通じて各tabに必要なComponentをレンダリングすることができます
* DashboardをComponent化することで、コードの再利用率を高め、機能を簡単に使用することができます
* Componentの追加に伴い、WindowsユーザーのWeb上で表示されるスクロールバーの表示を変更しました
* Componentごとにフォルダを整理しましたので、ご確認ください
* なし
- #49 
- #51 
- [공통 컴포넌트(共通 コンポーネント)](https://trello.com/c/1PzRmtEo/88-%EA%B3%B5%ED%86%B5-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8%E5%85%B1%E9%80%9A-%E3%82%B3%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%8D%E3%83%B3%E3%83%88)
- なし
* P3 : …

Dashboard Componentの機能とレイアウトの作成

---

src/components/dashboard/Dashboard.tsx

* 文字の長さによってtabのサイズが変動しない問題をこのPRで解決しようとします。
* tabの最小幅と最大範囲が設定されました。
* なし
* tabの幅の変更に関しては、このPRを参考に変更していただければと思います。
* なし
- #64 
- なし

Dashboard Componentのスタイル変更

---

src/app/components/card/Card.tsx
src/app/components/card/Invitation.tsx
src/components/dashboard/Dashboard.tsx
src/components/dashboard/TabsMapping.tsx
src/interfaces/dashboard/dashboardProps.ts
src/interfaces/dashboard/index.ts
src/interfaces/dashboard/tabsMappingProps.ts
src/interfaces/group/cardProps.ts
src/interfaces/group/index.ts
src/interfaces/group/invitationProps.ts

- ウェブコンソールで発生する警告問題を消去します
- interfaceファイル管理をより容易にすることができます
- Image Componentのprops内容とInterfaceのフォルダー構想が変わりました
- なし
- Next.JSが13ヴァージョンでアップデートについて、使わないpropsがあるので、気を付けてください
- なし
- #68 
- #69 
- なし

ウェブコンソールで発生する警告の除去とexportルールによるinterfaceファイルの修正

---

src/app/globals.css
src/app/layout.tsx
src/components/navbar/Navbar.tsx
src/styles/variable.css

* Navbar-componentと共通レイアウトのCSSを修正してユーザーエクスペリエンスを改善しようとします。 
* Navbar-componentのCSSを修正し、それに合わせて共通レイアウトのCSSも調整しました。 
* なし 
* なし 
* なし 
- #71 
- [메뉴바( メニューバー)](https://trello.com/c/zaFTQx8D/47-%EB%A9%94%EB%89%B4%EB%B0%94-%E3%83%A1%E3%83%8B%E3%83%A5%E3%83%BC%E3%83%90%E3%83%BC)
- なし

Navbar-componentと共通レイアウトCSSの修正作業

---

src/api/apiUtils.ts
src/api/httpStatus.ts

* このPRは、コードの重複性と可読性の問題を解決するためのものです。 これをaxiosを通じて機能化し、一箇所で管理できるようになりました。
* APIリクエストを関数化することで、コードの重複を最小限に抑え、読みやすさを向上させました。
* APIリクエストで受け取るstatus値を列挙型で管理し、読みやすさを向上させました。
* axiosを使ったAPIリクエストの機能化の部分を見ていただければ幸いです。
* なし
- #76 
- なし

axiosを活用したAPIリクエストの機能化

---

src/api/apiUtils.ts

* API関数の型定義の変更により、ジェネリック型を削除し、各関数呼び出し時に型を指定できるようにすることで、コードの再利用性とメンテナンス性を向上させました。
* API関数からジェネリック型を削除し,各API関数呼び出し時に型を指定するようにコードを修正しました。
* 既存のNestのurlが修正されました
* 型定義の変更により、API関数の呼び出し方に影響があります。もしerrorがあったら話してください。
* なし
- #83 
- なし

API関数のタイプ定義の改善による開発効率及び保守性の向上

---

src/api/material/getMaterial.ts
src/components/navbar/Navbar.tsx
src/components/navbar/material/MaterialContainer.tsx
src/components/navbar/material/MaterialForm.tsx
src/components/navbar/material/MaterialList.tsx
src/components/navbar/material/index.ts
src/components/navbar/profile/Profile.tsx
src/components/navbar/profile/index.ts
src/interfaces/navbar/index.tsx
src/interfaces/navbar/material.ts
src/interfaces/navbar/userProps.ts
src/model/User.ts

* 既存の単一構造になっていたNavbar Componentsを細分化して再設計し、関連データを要求するAPI関数を開発しました。 これにより、Navbarの機能を向上させ、ユーザーエクスペリエンスを改善しようとします。
* Navbar-componentを複数のサブcomponentに細分化して構造を再設計し、拡張性と保守性を改善しました。
* Navbarに関連するデータをサーバーから要求して処理できるAPIリクエスト関数を開発しました。
* 現在ログイン機能が構築されていないため、test用のuserモデルを作成しました。
* 細分化されたcomponentの構造とAPIリクエスト関数の実装方法について検討していただければ幸いです。
* APIリクエストと応答処理の正確性と例外状況に対する処理を重点的にテストする必要があります。 また、様々な環境での互換性テストも必要です。
- #84 
- [메뉴바( メニューバー)](https://trello.com/c/zaFTQx8D/47-%EB%A9%94%EB%89%B4%EB%B0%94-%E3%83%A1%E3%83%8B%E3%83%A5%E3%83%BC%E3%83%90%E3%83%BC)
* P1 : 必ず反映してください (Request Changes) - …

Navbar Componentの再設計と関連APIの開発でユーザーエクスペリエンスを向上させました。

---

__tests__/__snapshots__/snapshot.js.snap
package.json
yarn.lock

* このPRで、Jestタイプの定義がない問題を解決して、スナップショットテストが最新の状態に変更するためです。
* Jestタイプの定義を追加し、スナップショットテストを更新しました。
* なし
* Jestタイプの定義が正しく追加されたか、`index.test.tsx`ファイルと更新された`snapshot.js.snap`ファイルを確認してください。
* `yarn jest` コマンドで基本的なテスト作業が正常に行われることを確認してください。
- #89 

Jestタイプのインストールとスナップショットテストの更新

---

__tests__/api/getMaterial.test.ts
jest.config.ts
src/api/apiUtils.ts
src/api/material/getMaterial.ts

* APIリクエストURLをpropsで動的に変更できるように機能を実装しました。 これにより、柔軟なAPI設計が可能になりました。 また、getMaterial関数のテストコードを作成し、コードの安定性をさらに確保しました。
* apiUtilsファイル内でpropsで受け取った値によってAPIリクエストURLを動的に設定できる機能が追加されました。
* getMaterial関数のテストコードが作成され、関数の動作が期待通りに正確に行われることを検証できるようになりました。
* テストコードが正常に動作することを確認していただければ幸いです。
* getMaterial関数のテストコードが新しく追加されました。このテストコードが全てのケースをカバーしているか確認が必要です。
- #91 
- #81 
- なし

APIリクエストURLの動的変更実装による拡張性と保守性の向上

---

__tests__/api/getCheckClassSecret.test.ts
__tests__/api/getClass.test.ts
__tests__/api/verifySecret.test.ts
src/api/_class/getCheckClassSecret.ts
src/api/_class/getClasses.ts
src/app/[className]/components/card/PostCard.tsx
src/app/[className]/components/main/Main.tsx
src/app/components/card/Card.tsx
src/app/components/card/Invitation.tsx
src/app/components/group/Invite.tsx
src/app/components/group/Joined.tsx
src/app/components/group/Main.tsx
src/app/components/group/Waiting.tsx
src/app/components/group/modal/ClassCreate.tsx
src/app/components/group/modal/ClassPassword.tsx
src/app/components/group/modal/ClassWait.tsx
src/app/components/group/modal/index.ts
src/interfaces/group/cardProps.ts
src/interfaces/group/classProps.ts
src/interfaces/group/index.ts
src/interfaces/group/invitationProps.ts
src/interfaces/group/inviteProps.ts
src/interfaces/group/modal/classPasswordProps.ts
src/interfaces/group/modal/classWaitProps.ts
src/interfaces/group/modal/index.ts
src/interfaces/group/modal/modalProps.ts
src/model/User.ts
tsconfig.json

* このPRは、クラス照会と参加APIの追加、承認待ち、招待関連のモーダル修正により、ユーザーエクスペリエンスを向上させることを目的としています。
* クラス照会と参加のための新しいAPIを追加しました。
* 承認待ちと招待関連モーダルのを追加しました。
* クラスのメインページで`Image`の props関連のスタイルを変更しました。
* 新しく追加したAPIの機能が正常に動作することを確認してください。
* 新しいAPIのテストコードを作成したので、セキュリティ上の問題があれば教えてください。
- #77
- #94 
- #96

クラス参加と照会APIの追加

---

src/app/[className]/[materialName]/components/ManageContainer.tsx
src/app/[className]/[materialName]/components/ManageMaterialContainer.tsx
src/app/[className]/[materialName]/components/Material.tsx
src/app/[className]/[materialName]/components/index.ts
src/app/[className]/[materialName]/components/manageSubComponents/ManageSubContainer.tsx
src/app/[className]/[materialName]/page.tsx
src/styles/variable.css

* managePromptページの共通レイアウトを作成し、それに必要なCSSを作成しました。
* managePromptの全般的なレイアウトの作成です。
* CSSを追加しました。
* 全般的なレイアウトの問題がないのかみてください。
* なし
- #102 
- [관리자 프롬프트 페이지(管理者プロンプトページ））](https://okura-minori.atlassian.net/jira/core/projects/MIN/list?selectedIssue=MIN-75)

managePrompt共通レイアウトの作成

---

src/api/classUser/putUserName.ts
src/api/material/deleteMaterial.ts
src/api/material/patchMaterial.ts
src/api/material/postMaterial.ts
src/api/material/searchMaterial.ts
src/api/prompts/postPromptAccess.ts
src/components/navbar/Navbar.tsx
src/components/navbar/material/MaterialContainer.tsx
src/components/navbar/material/MaterialForm.tsx
src/components/navbar/material/MaterialList.tsx
src/components/navbar/material/index.ts
src/components/navbar/profile/EditName.tsx
src/components/navbar/profile/Profile.tsx
src/components/warning/Warning.tsx
src/interfaces/error/errorProps.ts
src/interfaces/error/index.ts
src/interfaces/navbar/editProps.ts
src/interfaces/navbar/formProps.ts
src/interfaces/navbar/index.ts
src/interfaces/navbar/paramsProps.ts
src/model/User.ts

* このissueの目的は、navbarのデザイン修正やnavbarで必要とする資料やニックネーム修正などのapiを繋げることです。
* navbarレイアウトのデザインが変更され、ニックネームの修正や資料CRUDなどのapi関数が追加されました。
* コンポーネントに合わせたinterfaceを追加し、propsを修正しました。
* 追加したapiが正常に動作することを確認していただければ幸いです。
* 追加したapiが正常に動作するかどうかテストが必要です。
- #71 
- #84 
- [메뉴바( メニューバー)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-60)
- なし

Navbar layout修正とapi接続

---

.gitignore
src/components/navbar/Navbar.tsx

* Node環境でwindowオブジェクトを使うことによるバグを修正することです。
* 今までwindowオブジェクトを使ってたのをuseRouterを使うように修正しました。
* gitignoreファイルに.envファイルを追加しました。
* なし
* なし
- #71 
- なし

Node環境でwindowオブジェクトの使用によるバグ修正

---

src/api/feedback/deleteFeedback.ts
src/api/feedback/getFeedback.ts
src/api/feedback/getFeedbacks.ts
src/api/feedback/getKeywords.ts
src/api/feedback/postFeedback.ts
src/api/prompts/getMessage.ts
src/api/prompts/postPrompt.ts
src/app/[className]/[materialName]/components/FeedbackContainer.tsx
src/app/[className]/[materialName]/components/FeedbackForm.tsx
src/app/[className]/[materialName]/components/FeedbackKeywordList.tsx
src/app/[className]/[materialName]/components/FeedbackList.tsx
src/app/[className]/[materialName]/components/ManageContainer.tsx
src/app/[className]/[materialName]/components/UserContainer.tsx
src/app/[className]/[materialName]/components/subComponents/ChatInput.tsx
src/app/[className]/[materialName]/components/subComponents/ClassChat.tsx
src/app/[className]/[materialName]/components/subComponents/PromptChat.tsx
src/app/[className]/[materialName]/components/subComponents/Storage.tsx
src/app/[className]/[materialName]/components/subComponents/SubContainer.tsx
src/app/[className]/[materialName]/page.tsx
src/interfaces/feedback/feedback.ts
src/interfaces/feedback/index.ts
src/interfaces/feedback/keyWord.ts
src/interfaces/prompt/index.ts
src/interfaces/prompt/inputProps.ts
src/styles/variable.css

* プロンプトページレイアウト作成を作成し、プロンプトに合わせたapi関数を生成して接続することです。
* プロンプトページのレイアウトが追加され、api関数が追加されました。
* プロンプトページ内でheightを調整するためCSSファイルを修正しました。
* apiが正常に動作しているかどうか見ていただけると幸いです。
* apiが正常に動作するかどうかテストコードが必要です。
- #92 
- #93 
- #102 

プロンプトページレイアウトの作成とapi関数の連携

---

package.json
src/app/intro/googleLogin/page.tsx
src/app/layout.tsx
src/components/navbar/Navbar.tsx
src/components/navbar/profile/Profile.tsx
src/components/protect/Protect.tsx
src/components/protect/index.ts
src/recoil/atoms/isLoginState.ts
src/recoil/atoms/userState.ts
yarn.lock

* 更新時にrecoilデータが飛んでしまい、再ログインしなければならない問題を解決しました。
* recoil persistライブラリを追加し、ログイン状態を維持するように修正しました。
* ログイン状態維持に合わせてコンポーネント内のデータを修正しました。
* リフレッシュ時にrecoilデータが維持されていることを確認していただければ幸いです。
* なし
- #104 
- #115 
- なし

recoil persistライブラリを追加し、ログイン状態を維持するように修正

---

src/api/apiUtils.ts
src/app/intro/page.tsx
src/components/navbar/profile/Profile.tsx

* refresh-tokenを利用して再発行する過程で発生するエラーを解決し、ログアウトロジックを修正しました。
* refreshtoken ロジックとログアウトロジックです。
* なし
* ロジックが正常に動作することを確認していただければ幸いです。
* なし
- #104 
- [로그인 페이지(ログインページ)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-71)
- なし

ログインロジック修正とログアウト修正

---

src/app/[className]/[materialName]/components/subComponents/PromptChat.tsx
src/app/[className]/[materialName]/components/subComponents/Storage.tsx
src/app/[className]/[materialName]/components/subComponents/SubContainer.tsx
src/app/[className]/[materialName]/page.tsx
src/components/navbar/material/MaterialList.tsx
src/interfaces/navbar/material.ts
src/recoil/atoms/materialState.ts

* 静的に動いていたmaterialデータをstateを通じて静的に動くように修正しました。
* material stateを追加してデータを受け取れるようにし、それに合わせてコンポーネント内でapiリクエスト関数に必要なデータを更新しました。
* なし
* material state の値が正しく動作することを確認していただければ幸いです。
* なし
- #93 
- なし

materialの状態管理追加 materialコンポーネントの修正

---

src/api/classUser/getClassInfo.ts
src/api/feedback/getFeedback.ts
src/api/material/patchMaterial.ts
src/api/prompts/postPrompt.ts
src/app/Loading.tsx
src/app/[className]/[materialName]/components/FeedbackContainer.tsx
src/app/[className]/[materialName]/components/FeedbackForm.tsx
src/app/[className]/[materialName]/components/FeedbackKeywordList.tsx
src/app/[className]/[materialName]/components/Material.tsx
src/app/[className]/[materialName]/components/subComponents/SubContainer.tsx
src/app/[className]/[materialName]/page.tsx
src/app/layout.tsx
src/components/footer/Footer.tsx
src/components/navbar/Navbar.tsx
src/components/navbar/material/MaterialContainer.tsx
src/components/navbar/material/MaterialForm.tsx
src/components/navbar/material/MaterialList.tsx
src/components/navbar/profile/Profile.tsx
src/interfaces/navbar/formProps.ts

* materialコンポーネントとnavbarコンポーネントのpropsとapi関数を修正しました。
* materialコンポーネントとpromptで使うapi関数リクエストに必要なデータを修正し、それに合わせてpropsを修正しました。
* streaming fetch要求を一定に修正しました。
* apiリクエストが正常に動作していることを確認していただければ幸いです。
* なし
- #92 
- #93 
- #102 
- なし

materialコンポーネントとnavbarコンポーネントのpropsとapi関数を修正

---

src/app/[className]/[materialName]/components/Material.tsx

- Materialコンポーネントが他のコンポーネントの領域を侵害してしまう問題を解決したいです。デザインの一貫性とユーザーインターフェースの品質を向上させることが目的です。
- 特定のMaterialコンポーネントのCSSを調整し、他のコンポーネントの領域に重ならないようにしました。この変更により、インターフェースの見た目が改善され、ユーザーの操作性が向上しました。
- なし
- CSSの変更が他のコンポーネントに予期せぬ影響を与えていないか、特にレスポンシブデザインの観点から確認していただきたいです。
- 変更したCSSが異なるブラウザやデバイスで予定通りに動作するかの検証が必要です。特に、モバイルデバイスとデスクトップデバイスの両方でのテストをお願いします。
- #123 
- [유저 프롬프트 페이지(ユーザープロンプトページ）](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-89)
- [관리자 프롬프트 페이지(管理者プロンプトページ）](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-75)
- 変更前後のスクリーンショットを添付します。変更後はMaterialコンポーネントが他のコンポーネントと正しく調和していることがわかります。
* …

MaterialコンポーネントのCSSを修正

---

src/app/[className]/[materialName]/components/FeedbackContainer.tsx
src/app/[className]/[materialName]/components/FeedbackForm.tsx
src/app/[className]/[materialName]/components/FeedbackList.tsx
src/app/[className]/[materialName]/components/Material.tsx
src/app/[className]/[materialName]/components/Quiz.tsx
src/app/[className]/[materialName]/components/UserContainer.tsx
src/app/[className]/[materialName]/page.tsx
src/app/[className]/components/card/PostCard.tsx
src/app/[className]/components/card/ScheduleCard.tsx
src/app/[className]/components/main/Main.tsx
src/app/[className]/components/main/Notice.tsx
src/app/[className]/components/main/Post.tsx
src/app/[className]/components/main/Schedule.tsx
src/app/[className]/components/modal/ClassCreatePost.tsx
src/app/[className]/components/modal/ClassCreateSchedule.tsx
src/app/[className]/components/modal/ClassPost.tsx
src/app/[className]/page.tsx
src/app/components/_class/Main.tsx
src/app/components/_class/modal/ClassCreate.tsx
src/app/intro/components/login/Login.tsx
src/app/intro/page.tsx
src/components/navbar/Navbar.tsx
src/components/navbar/material/MaterialContainer.tsx
src/components/navbar/material/MaterialForm.tsx
src/components/navbar/material/MaterialList.tsx
src/components/navbar/profile/EditName.tsx
src/components/navbar/profile/Profile.tsx

- 発表の際、聴衆が英文を見て読みやすさに問題が発生する可能性があるため、これを修正する必要があります。
- 英語で表記されている表記を韓国語に変更しました。
- なし
- 他の部分に英文がある場合は、韓国語に変更してください。
- なし
- #122 
- なし

発表前の英文をハングルに変更する作業

---

src/api/_class/index.ts
src/api/_class/patchClassRole.ts
src/api/_class/patchToggleFavoriteClass.ts
src/api/classSchedule/index.ts
src/api/classSchedule/patchClassSchedule.ts
src/app/classes/components/card/Card.tsx

* ビルド前に未使用のコードが原因で発生するエラーを除去します。
* 未使用のAPIコードを削除
* なし
* またエラーが発生しないか確認してください。
* なし
- #134 
- なし

ビルド前に使わないコードの整理

---

.github/workflows/ci.yml
Dockerfile

* #36 
* [프론트엔드(Next.js) 파이프라인 구축(フロントエンドパイプラインの構築)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-176)
* Dockerfileの修正:
- `canvas`モジュールのために `python3`, `make`, `g++`の依存関係を追加しました。
- Python依存関係を含めるため、`yarn install`ステップを更新しました。
* ci.ymlの修正:
- ECRリージョンを `ap-northeast-2` に修正しました。
* なし
* DockerfileとCI/CDパイプラインの変更が適切であるかどうか。
* なし
* #36 
* [프론트엔드(Next.js) 파이프라인 구축(フロントエンドパイプラインの構築)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-176)
* P1 : 必ず反映してください …

[MIN-176] DockerfileとCI/CDパイプラインの修正でNext.jsデプロイを改善

---

.github/workflows/cicd.yml

* ECSへの自動デプロイをGitHub Actionsで実装することで、mainブランチにプッシュされるたびに最新のDockerイメージがECRにプッシュされ、自動的にECSサービスが更新されるようにします。
* #140
* [프론트엔드(Next.js) 파이프라인 구축(フロントエンドパイプラインの構築)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-176)
GitHub Actionsワークフローを追加し、以下の機能を実装しました：
* コードのチェックアウト
* AWSクレデンシャルの設定
* DockerイメージのビルドとECRへのプッシュ
* ECSサービスの自動更新
* なし
* ECSサービスの自動更新部分が正しく設定されているかどうかを特に確認していただきたいです。
* GitHub Actionsワークフローが正常に動作することを確認するためのテスト
* ECRへのDockerイメージのプッシュが成功することを確認するためのテスト
* ECSサービスが新しいDockerイメージを使用して正しくデプロイされることを確認するためのテスト
* #140
* [프론트엔드(Next.js) 파이프라인 구축(フロントエンドパイプラインの構築)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-176)
* …

[MIN-176] ECSへの自動デプロイをGitHub Actionsで実装

---

src/api/baseUrl.ts

- nginxのロードバランサー設定をテストするため、APIリクエストを実行するためのアドレスを変更しました。
- nginxのロードバランサー設定をテストするため、APIリクエストを実行するためのアドレスを変更しました。
- なし
- 新しいAPIリクエストアドレスが正しく設定されていることを確認してください。
- この変更に関連するテストや検証が必要です。
- #138 
- この段階では視覚的な素材は用意していませんが、必要であればUIのフローを説明するスクリーンショットを追加します。

nginx設定のためAPIリクエストアドレスの修正

---

Dockerfile

* Dockerfileの最適化によるビルドとランタイムのパフォーマンス向上
* 依存関係のインストールとビルドプロセスを分けることで最終イメージサイズを最小化し、効率的なビルドプロセスを実現
* #140 
* [프론트엔드(Next.js) 파이프라인 구축(フロントエンドパイプラインの構築)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-176)
* Dockerfileをマルチステージビルドに変更し、ビルド効率と最終イメージサイズを最適化
* 必要な依存関係のみをインストールするために、production環境用のステージを追加
* 不要なファイルを排除し、production環境用に最適化されたランタイム環境を構築
* なし
* Dockerfileの最適化が期待通りのパフォーマンス向上を達成しているかどうか
* Dockerfileの変更により、ビルドとランタイムの動作確認
* #140 
* [프론트엔드(Next.js) 파이프라인 구축(フロントエンドパイプラインの構築)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-176)
* …

[MIN-176] Dockerfileの最適化によるNext.jsアプリケーションのビルドおよびランタイム性能の向上

---

README.md

* README.mdにプロジェクトのディレクトリ構造を追加して、新しい貢献者がプロジェクトのレイアウトを理解しやすくします。
* #144 
* README.mdにディレクトリ構造のセクションを追加しました。
* プロジェクトの主要なディレクトリとその説明を含めました。
* なし
* ディレクトリ構造の説明が正確で理解しやすいかどうか
* 特にありませんが、README.mdの内容が適切かどうか確認してください。
* #144 

README.mdにディレクトリ構造を追加

---

package.json
src/api/_class/index.ts
src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
src/app/classes/[cId]/[mId]/components/manageSubComponents/ManageSubContainer.tsx
src/app/classes/[cId]/[mId]/components/subComponents/LiveClassViewer.tsx
src/app/classes/[cId]/[mId]/components/subComponents/SubContainer.tsx
yarn.lock

- ビデオチャット機能の実装のために、フロントエンドコードをアップロードしました。
- ビデオチャットのユーザーインターフェースと機能を提供するためのフロントエンドコードを追加しました。
- ユーザーがビデオチャットに参加するためのUIと操作ロジックが含まれています。
- なし
- ビデオチャットのフロントエンドが正しく機能するか、UIが適切かどうかを確認してください。
- ビデオチャットの接続テストとUI操作のテストが必要です。
- [ビデオチャットフロントエンドコードのアップロード](#148 )
- この段階では視覚的な素材は用意していませんが、必要であればUIのフローを説明するスクリーンショットを追加します。

ビデオチャットフロントエンドコードのアップロード

---

src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
src/app/classes/[cId]/[mId]/components/subComponents/LiveClassViewer.tsx

- 開発を進めるために、ビデオチャットの基本的なレイアウトを作成しました。
- ビデオチャットの基本レイアウトを追加しました。
- ユーザーインターフェースの各コンポーネントを初期配置しました。
- なし
- レイアウトが適切にデザインされているか、UIの基本的な配置が正しいか確認してください。
- レスポンシブデザインの確認と、異なるデバイスでの表示確認が必要です。
- [ビデオチャットの基本レイアウトの作成](#150 )
- この段階では視覚的な素材は用意していませんが、必要であればUIのフローを説明するスクリーンショットを追加します。

ビデオチャットの基本レイアウトの作成

---

src/app/classes/[cId]/[mId]/components/UserContainer.tsx
src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
src/app/classes/[cId]/[mId]/components/subComponents/LiveClassViewer.tsx
src/app/classes/[cId]/[mId]/components/subComponents/SubContainer.tsx

- ビデオチャット機能を実装しました。これにより、ユーザーが遠隔でチャットを行うことが可能になります。
- ビデオチャットのバックエンド機能を追加しました。
- フロントエンドとバックエンドの連携を確認し、正常に動作することを確認しました。
- ユーザーインターフェースにビデオチャット用のコンポーネントを追加しました。
- なし
- ビデオチャットの接続品質とユーザーインターフェースの使い勝手を特に確認してください。
- ビデオチャットの機能テストを行い、異なるデバイス間での接続を確認してください。
- ビデオチャット中のパフォーマンスや遅延の確認も必要です。
- [ビデオチャットの実装](https://github.com/YJU-OKURA/project_minori-next-deployment-repo/issues/154)
- ビデオチャットのUIと機能が正常に動作することを確認するためのスクリーンショットや動画を後ほど提供します。

ビデオチャットの実装

---

src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
src/app/classes/[cId]/[mId]/components/subComponents/LiveClassViewer.tsx

- ビデオチャット機能で不必要に使用されていた入力欄を削除しました。これにより、ユーザーインターフェースがシンプルになり、ユーザーエクスペリエンスが向上します。
- ビデオチャット画面から不要な入力欄を削除しました。
- なし
- ビデオチャット画面のUIが正しく表示されるか、特に確認してください。
- 不要な入力欄が確実に削除されているか確認してください。
- ビデオチャット機能の動作確認を行い、削除された入力欄がユーザーエクスペリエンスにどのように影響するかを確認してください。
- [ビデオチャットの実装](https://github.com/YJU-OKURA/project_minori-next-deployment-repo/issues/154)
- 不要な入力欄が削除されたビデオチャット画面のスクリーンショットを後ほど提供します。

使っていない inputの削除

---

src/api/feedback/getFeedback.ts
src/api/material/patchMaterial.ts
src/api/prompts/patchMessage.ts
src/api/prompts/postPrompt.ts
src/app/classes/[cId]/[mId]/components/FeedbackKeywordList.tsx
src/app/classes/[cId]/[mId]/components/FeedbackList.tsx
src/app/classes/[cId]/[mId]/components/QuizFeedback.tsx
src/app/classes/[cId]/[mId]/components/QuizList.tsx
src/app/classes/[cId]/[mId]/components/QuizReport.tsx
src/app/classes/[cId]/[mId]/components/QuizSet.tsx
src/components/navbar/Navbar.tsx
src/components/navbar/material/MaterialContainer.tsx
src/components/navbar/material/MaterialList.tsx
src/interfaces/quiz/users.ts
src/interfaces/user/ClassUser.ts

* Quizコンポーネントに必要な状態チェック要素を追加して問題を解決しました。
* Quizコンポーネントにステータスチェックが追加されたこのです。
* navbarの間隔が合わないレイアウトのデザインを修正しました。
* 状態チェックが正しく行われていることを確認してください。
* 状態チェックのテストが必要です。
- #102 
- なし

navbarのレイアウトを修正し、Quizコンポーネントにステータスチェックを追加。

---

src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
src/app/classes/[cId]/[mId]/components/subComponents/LiveClassViewer.tsx

- ビデオチャット機能において、ユーザーがマイクとカメラをオン/オフできる機能を実装しました。これにより、ユーザーのプライバシーが向上し、必要に応じて音声と映像をコントロールできるようになります。
- ビデオチャット画面にマイクのオン/オフボタンを追加しました。
- ビデオチャット画面にカメラのオン/オフボタンを追加しました。
- 各ボタンが適切に機能するためのロジックを実装しました。
- なし
- マイクとカメラのオン/オフ機能が正しく動作するか、特に確認してください。
- UIがユーザーフレンドリーであるかどうかを確認してください。
- マイクとカメラのオン/オフ機能に対する統合テストを実施してください。
- 各ボタンの動作確認を行い、意図した通りに機能することを確認してください。
- [マイクとカメラをオン/オフする機能の実装](https://github.com/YJU-OKURA/project_minori-next-deployment-repo/issues/158)
- 新しいオン/オフ機能が追加されたビデオチャット画面のスクリーンショットを提供します。
- レビュアーはコードレビュー時に良いコードの方向性を示しますが、コード修正を強制することはありません。
- レビュアーは良いコードを見つけた場合、賞賛と励ましを惜しみません。
- レビューは特別なケースでない限り、レビュアーに指定された時点から3日以内に行ってください。
- コメント作成時にPrefixにP1、P2、P3を書いていただくと、Assigneeがより明確にコメントに対して対応することができます。
- P2 : 反映を積極的に検討していただければと思います …

マイクとカメラをオン/オフする機能の実装

---

src/app/classes/[cId]/[mId]/components/UserContainer.tsx
src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
src/app/classes/[cId]/[mId]/components/subComponents/LiveClassViewer.tsx

- express基盤のサーバーコードを新たにアップロードしました。この変更により、サーバーのパフォーマンスとセキュリティが向上します。
- 関連ドキュメントや設計図は特にありませんが、標準的なサーバー管理機能の一環として実装されました。
- サーバーの基盤をexpressに移行し、新しいルーティングとミドルウェアが追加されました。
- サーバーのパフォーマンスが向上し、セキュリティ対策が強化されました。
- なし
- 新しいexpress基盤のセキュリティ対策が適切かどうか、特に確認いただきたいです。
- 新しいサーバーコードの統合テストと、ルーティングのテストが必要です。
- 現時点で特に関連するIssueやドキュメントはありません。
- この段階では視覚的な素材は用意していませんが、必要であればサーバーの動作を説明するスクリーンショットを追加します。
* P1 - 必ず反映してください (Request Changes) - 問題が発生したり、脆弱性が発見されたケースなど。
* P2 - 反映を積極的に検討していただければと思います (コメント)。
* P3 - こんな方法もあるんじゃないかな～などの些細な意見です (Chore)。

ユーザーＩＤが確認できなかった現象の改善

---

src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
src/app/classes/[cId]/[mId]/components/subComponents/LiveClassViewer.tsx

* 現在のWebRTC接続は、NATやファイアウォールの制限により、直接的なピアツーピア接続が困難な場合があります。これにより、異なるPC間での接続に問題が発生しています。このPRでは、TURNサーバーを導入することで、これらの環境下でも信頼性の高い接続を確保し、接続性を向上させることを目的としています。
- TURNサーバーの設定を追加しました。
- `urls`: TURNサーバーのURL
- `username`: 認証に必要なユーザー名
- `credential`: 認証に必要なパスワード
- TURNサーバーの設定を利用して、接続の信頼性を向上させました。
- `WebSocket`接続の安定性を向上させるため、エラーハンドリングとログ出力の改善を行いました。
- TURNサーバー設定が正しく追加されているか。
- ICE候補の交換が適切に行われているか。
- リモートピアとの接続が問題なく確立されるかどうか。
- 異なるネットワーク環境での接続テスト
- ファイアウォールやNATの背後にいるクライアント間での接続テスト
- TURNサーバーを介したメディアストリームの送受信確認 …

TURNサーバー設定の追加によるWebRTC接続性の向上

---

src/api/classUser/getClassMember.ts

* 不足していたapiリクエスト関数ファイルを追加しました。
* 不足しているファイルを追加しました。
* なし
* apiリクエストが正しく入力されていることを確認してください
* apiリクエスト関数が正常に動作することをテストしてください。
- #102 
- なし

不足しているapiリクエスト関数ファイルを追加

---

src/app/classes/[cId]/[mId]/components/chatComponents/page.tsx
src/app/classes/[cId]/[mId]/components/manageSubComponents/ManageSubContainer.tsx
src/app/classes/[cId]/components/main/Post.tsx

- ライブチャットと投稿のデザインを修正しました
- レイアウトの配置、margin値が変更されました
- なし
- 支援前にテストしてください
- なし
- #167
- なし

ライブチャットと投稿のデザイン修正

---

src/api/baseUrl.ts

* Mixed Contentエラーの解決
* `http://43.203.66.25/api/gin` から `https://43.203.66.25/api/gin` への変更
* なし
* APIリクエストのURL変更により、HTTPS通信が正しく行われているか確認していただきたいです。
* ページが正しくHTTPSでロードされ、APIリクエストがMixed Contentエラーなしで正常に動作していることを確認する必要があります。

🐛 fix: ginサービスのAPI URLをHTTPSに変更

---

src/api/baseUrl.ts

* 開発環境で使用していたAPI Base URLを本番環境用に更新する必要があります。これにより、アプリケーションが本番環境で正しく動作するようになります。
* `gin` APIのURLを `https://minoriedu.com/api/gin` に更新しました。
* `nest` APIのURLを `https://minoriedu.com/api/nest` に更新しました。
* 開発環境用のURLをコメントアウトして、将来の参照用に保持しました。
* なし
* URLの更新が正しく行われているか確認をお願いします。
* 開発環境用URLのコメントアウトが適切かどうかご意見をいただけると幸いです。
* 更新されたURLで各APIエンドポイントに正しくアクセスできることを確認する必要があります。
* 本番環境でのE2Eテストを実施し、アプリケーション全体が正常に動作することを確認してください。
* P1 : 必ず反映してください …

🔨 本番環境デプロイ用のAPI Base URLを更新

---

src/api/prompts/postPrompt.ts

* URLがハードコード化されているため、可読性や保守性が低いという問題を解決するため、これを定数に変更することでコードの再利用性を高め、今後の管理の利便性を図ることが目的です。
* ハードコードされたAPI URLを定数に変更しました。
* なし
* なし
* API呼び出しが正常に動作することを確認する必要があります。追加のテストコードが必要な場合は記載する予定です。
- #91 
- なし

URL修正及び定数化

---

src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx

* WebSocket接続が不安定で、頻繁に切断される問題
* スケーラビリティとパフォーマンスの制限
* 長時間接続時のタイムアウト問題
* WebRTC接続の安定性問題
* MediaSoupの設定が最適化されていない問題
* コンテナの再起動ポリシーが未設定
* Nginx WebSocket設定の強化
- `keepalive` 設定の追加
- タイムアウト値の最適化
- キャッシュとバッファリング設定の調整
* WebSocket接続の安定性向上のための追加設定
- `proxy_socket_keepalive` の有効化
- 長時間接続のサポート改善
* Docker実行設定の最適化
- UDP ポート範囲の適切な公開
- 環境変数の追加
- 再起動ポリシーの設定
* MediaSoup設定の改善
- NAT traversal の設定強化
- メディアストリームのビットレート最適化
* コンテナのログ管理設定の追加
* デバッグ用ヘッダーの追加
* エラーハンドリングの強化
* Nginx WebSocket設定の最適値
* MediaSoupのNAT traversal設定
* コンテナの再起動ポリシー
* タイムアウト値の妥当性
* 長時間接続の安定性テスト
* 多数のクライアント同時接続テスト
* 切断・再接続のハンドリングテスト
* メディアストリームの品質確認
* NAT環境での接続テスト
* コンテナの再起動動作確認
* リソース使用状況の監視
* …

🛠 ビデオチャットの設定改善：WebSocket と MediaSoup の設定最適化

---

src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx

> 実装した機能や解決した課題、PRを開くきっかけや目的をReviewerが理解しやすいように書いてください。 
> バックログのリンク、ダイアグラム、Figmaなどの関連ドキュメントを添付するとより良いです。
* 
> 問題を解決しながら、主な変更点を書いてください。
* 
> ない場合は「なし」と記載してください。
* 
> 開発過程で他の方の意見が気になったり、クロスチェックが必要だと感じたコードがあれば教えてください。
* 
> テストが必要な項目やテストコードが追加されたら一緒に書いてください。
* 

🐛 fix: WebSocket再接続ロジックおよび状態管理の改善
